version: "3.8"
services:
  dotfiles:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dotfiles-test
    image: benmezger/dotfiles:latest
    environment:
      - CI=1
      - HOME=/home/archie
    volumes:
      - .:/home/archie/dotfiles
    working_dir: /home/archie/dotfiles
    user: archie
