#!/usr/bin/env zsh

ZSH_THEME="robbyrussell"

plugins=(
    git
    zsh-autosuggestions
)

if [[ "$ZPROF" = true ]]; then
        zmodload zsh/zprof
fi

if [ -f "$HOME/.zsh_plugins.sh" ]; then
        source $HOME/.zsh_plugins.sh
else
        echo "Bundling zsh plugins..."
        antibody bundle <$HOME/.zsh/plugins.txt >$HOME/.zsh_plugins.sh
        source $HOME/.zsh_plugins.sh
fi

source $HOME/.zsh/init.zsh
source $HOME/.zsh/evals.zsh
source $HOME/.zsh/history.zsh
source $HOME/.zsh/stack.zsh
source $HOME/.zsh/keys.zsh
source $HOME/.zsh/aliases.zsh
source $HOME/.zsh/gpg-agent.zsh
source $HOME/.zsh/exports.zsh

if [ -f "$HOME/.cargo/env" ]; then
        source $HOME/.cargo/env
fi

# load base16 themes if on terminal
if [[ -n $DISPLAY ]]; then
        # base16 theme
        base16_gruvbox-dark-hard
fi

if (($+commands[fortune])); then
        fortune
fi

if [[ "$ZPROF" = true ]]; then
        exit_hook() {
                print "zprof for process $$"
                zprof

                while read input; do
                done

                exit 0
        }
        add-zsh-hook zshexit exit_hook
fi

# emacs(tramp): disable zsh line editor because zsh uses
# left-hand side and right-hand side prompts in parallel
# see: TRAMP does not connect to the remote host at
# https://www.gnu.org/software/emacs/manual/html_node/tramp/Frequently-Asked-Questions.html
[[ $TERM == "dumb" ]] && unsetopt zle && PS1='$ ' && return

# initialise completions with ZSH's compinit
autoload -Uz compinit
compinit

# opam configuration
[[ ! -r /home/willian/.opam/opam-init/init.zsh ]] || source /home/willian/.opam/opam-init/init.zsh  > /dev/null 2> /dev/null

# asdf configuration
. /opt/asdf-vm/asdf.sh

# append completions to fpath
fpath=(${ASDF_DIR}/completions $fpath)
