#!/usr/bin/env zsh

# Test if $1 is available
isavailable() {
    type "$1" &>/dev/null
}

# screen powersave
xset +dpms
xset dpms 0 0 300
xset r rate 180 40

# 230 has IPS or TN screen with 125.37 DPI
xrandr --dpi 125.37

# run xrdb
[[ -f $HOME/.Xresources ]] && xrdb -merge $HOME/.Xresources

# start redshift
# current lat/log: oud-zuid
isavailable synclient && synclient TouchpadOff=1 &

isavailable fastcompmgr && fastcompmgr &
isavailable nm-applet && nm-applet &
isavailable xautolock && xautolock -time 10 -locker ~/.bin/lock &
isavailable dunst && dunst -config ~/.config/dunst/dunstrc &
isavailable libinput-gestures-setup && libinput-gestures-setup start &
isavailable blueman-applet && blueman-applet &
isavailable setxkbmap && setxkbmap -option caps:escape &
isavailable xbindkeys && xbindkeys &
isavailable warpd && warpd &
isavailable gxkb && gxkb &
isavailable unclutter && unclutter -idle 2 -jitter 2 -root &
isavailable xmodmap && xmodmap $HOME/.Xmodmap

bash $HOME/.bin/lightsOn.sh &
/usr/lib/geoclue-2.0/demos/agent &

# Dell Inspiron 7560
#isavailable xinput && xinput set-prop \
    #"DELL0782:00 06CB:7E92 Touchpad" \
    #"libinput Natural Scrolling Enabled" 1 &


# Dell Inspiron 7560
#isavailable xinput && input set-prop \
    #"SYNA3602:00 093A:0255 Touchpad"\
    #"libinput Natural Scrolling Enabled" 1 &

# start some nice programs
if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi

exec dbus-launch --sh-syntax i3
