#!/usr/bin/env zsh

# Test if $1 is available
isavailable() {
    type "$1" &>/dev/null
}

# screen powersave
xset +dpms
xset dpms 0 0 300
xset r rate 180 40

# 230 has IPS or TN screen with 125.37 DPI
xrandr --dpi 125.37

# run xrdb
[[ -f $HOME/.Xresources ]] && xrdb -merge $HOME/.Xresources

# run urxvt daemon
[[ -z "$(pidof urxvtd)" ]] && urxvtd --quiet --opendisplay --fork

# start redshift
# current lat/log: oud-zuid
isavailable synclient && synclient TouchpadOff=1 &

isavailable picom && picom --config ~/.config/picom.conf &
isavailable nm-applet && nm-applet &
isavailable xautolock && xautolock -time 10 -locker ~/.bin/lock &
isavailable dunst && dunst -config ~/.config/dunst/dunstrc &
isavailable libinput-gestures-setup && libinput-gestures-setup start &
isavailable blueman-applet && blueman-applet &
isavailable setxkbmap && setxkbmap -option caps:escape &
isavailable xbindkeys && xbindkeys &
isavailable flameshot && flameshot &
isavailable warpd && warpd &

#start_nordvpn() {
    #while ! ping -c 1 -W 1 8.8.8.8; do                                                                                                                                                    [I]
        #echo "Waiting for 8.8.8.8 - network interface might be down..."
        #sleep 1
    #done

    #nordvpn connect
#}

#isavailable nordvpn && nordvpn account | grep -v "You are not logged in" && start_nordvpn &

#bash $HOME/.bin/lightsOn.sh &

/usr/lib/geoclue-2.0/demos/agent &

# Dell Inspiron 7560
# enable natural scrolling
isavailable xinput && xinput set-prop \
    "DELL0782:00 06CB:7E92 Touchpad" \
    "libinput Natural Scrolling Enabled" 1 &

# enable tapping
isavailable xinput && xinput --set-prop \
    "DELL0782:00 06CB:7E92 Touchpad" \
    "libinput Tapping Enabled" 1 &


# start some nice programs
if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi
