#!/usr/bin/env bash
CMD="kitty"

# Check if there is GPU support
if [[ $(command -v optirun 2>/dev/null) != "" ]]
then
    CMD="optirun kitty"
fi

selected_theme=$(gsettings get org.gnome.desktop.interface color-scheme)

mode="gruvbox_dark.conf"

if [ "$selected_theme" == "'prefer-light'" ]; then
        mode="gruvbox_light.conf"
fi

$CMD -o include="~/.config/kitty/kitty-themes/themes/"$mode
