#!/bin/bash
setxkbmap -layout us -variant intl

# Dell laptop
xrandr --output HDMI-1 --auto --right-of eDP-1
xinput set-prop "DELL0782:00 06CB:7E92 Touchpad" "libinput Tapping Enabled" 1
xinput set-prop "DELL0782:00 06CB:7E92 Touchpad" "libinput Natural Scrolling Enabled" 1

# Acer laptop
xrandr --output HDMI1 --auto --right-of eDP1
xinput set-prop "SYNA7DB5:01 06CB:CD41 Touchpad" "libinput Tapping Enabled" 1
xinput set-prop "SYNA7DB5:01 06CB:CD41 Touchpad" "libinput Natural Scrolling Enabled" 1

