#!/usr/bin/env bash
CMD="kitty"

# Check if there is GPU support
if [[ $(command -v optirun 2>/dev/null) != "" ]]
then
    CMD="optirun kitty"
fi

selected_theme=$(gsettings get org.gnome.desktop.interface color-scheme)

kitty_theme="Gruvbox Dark"

if [ "$selected_theme" == "'prefer-light'" ]; then
        kitty_theme="Gruvbox Light"
fi

kitty +kitten themes --reload-in=all $kitty_theme
$CMD
