#!/usr/bin/env bash

selected_theme=$(cat $HOME/.xsettingsd)

mode="prefer-dark"
gtk_theme="gruvbox-dark-gtk"
kitty_theme="Gruvbox Dark"
vim_theme="dark"

if [ "$selected_theme" == 'Net/ThemeName "gruvbox-dark-gtk"' ]; then
        mode="prefer-light"
        gtk_theme="gruvbox-light-gtk"
        kitty_theme="Gruvbox Light"
        vim_theme="light"
fi

echo "Theme:" $mode

kitty +kitten themes --reload-in=all $kitty_theme

echo "Net/ThemeName \"$gtk_theme\"" > $HOME/.xsettingsd
echo "set background=$vim_theme" > $HOME/.nvim.color

killall -HUP xsettingsd

