#!/usr/bin/env bash
CMD="kitty"

selected_theme=$(cat ~/.xsettingsd)

kitty_theme="Gruvbox Dark"

if [ "$selected_theme" == 'Net/ThemeName "gruvbox-light-gtk"' ]; then
        kitty_theme="Gruvbox Light"
fi

kitty +kitten themes --reload-in=all $kitty_theme
$CMD
