return {
    "tpope/vim-fugitive",
    "tpope/vim-git",
    "airblade/vim-gitgutter",
    "luochen1990/rainbow",
    "Yggdroot/indentLine",
    "wakatime/vim-wakatime",
    "scrooloose/nerdcommenter",
    "neovim/nvim-lspconfig",
    "williamboman/mason.nvim",
    "williamboman/mason-lspconfig.nvim",
    "hrsh7th/cmp-nvim-lsp",
    "hrsh7th/nvim-cmp",
    "L3MON4D3/LuaSnip",
    "onsails/lspkind.nvim",
    "kamailio/vim-kamailio-syntax",
    "APZelos/blamer.nvim",
    "nvim-lua/plenary.nvim",
    "nvim-telescope/telescope.nvim",
    "nvim-treesitter/nvim-treesitter",
    "nvim-treesitter/playground",
    "chriskempson/base16-vim",
    "ThePrimeagen/harpoon",
    "juneedahamed/vc.vim",
    "rust-lang/rust.vim",
    "github/copilot.vim",
    "editorconfig/editorconfig-vim",
    { "junegunn/fzf", build = "./install --all" },
    { "junegunn/fzf.vim" },
    "christoomey/vim-tmux-navigator",
    "vim-scripts/svnj.vim",
    "tpope/vim-dadbod",
    "kristijanhusak/vim-dadbod-ui",
    "kristijanhusak/vim-dadbod-completion",
    "nvim-neorg/neorg",
    "dhruvasagar/vim-zoom",
    "tjdevries/express_line.nvim",
    { "ellisonleao/gruvbox.nvim", priority = 1000 , config = true },
    { dir = "~/Documents/Projects/Random/ryak" },
}
