return {
    "tpope/vim-fugitive",
    "wakatime/vim-wakatime",
    "scrooloose/nerdcommenter",
    "neovim/nvim-lspconfig",
    "nvim-lua/plenary.nvim",
    "nvim-telescope/telescope.nvim",
    "nvim-treesitter/nvim-treesitter",
    "nvim-treesitter/playground",
    "williamboman/mason.nvim",
    "williamboman/mason-lspconfig.nvim",
    "hrsh7th/cmp-nvim-lsp",
    "hrsh7th/nvim-cmp",
    "L3MON4D3/LuaSnip",
    "onsails/lspkind.nvim",
    "kamailio/vim-kamailio-syntax",
    "ThePrimeagen/harpoon",
    "github/copilot.vim",
    { "junegunn/fzf", build = "./install --all" },
    { "junegunn/fzf.vim" },
    "christoomey/vim-tmux-navigator",
    "vim-scripts/svnj.vim",
    "tjdevries/express_line.nvim",
    { "ellisonleao/gruvbox.nvim", priority = 1000 , config = true },
    { dir = "~/Documents/Projects/Random/ryak" },
    "godlygeek/tabular",
    "airblade/vim-gitgutter",
    "folke/todo-comments.nvim"
    --"preservim/vim-markdown",
    --"tpope/vim-git",
    --"tpope/vim-eunuch",
    --"tpope/vim-dadbod",
    --"luochen1990/rainbow",
    --"Yggdroot/indentLine",
    --"nvim-neorg/neorg",
    --"APZelos/blamer.nvim",
    --"chriskempson/base16-vim",
    --"juneedahamed/vc.vim",
    --"rust-lang/rust.vim",
    --"editorconfig/editorconfig-vim",
    --"kristijanhusak/vim-dadbod-ui",
    --"kristijanhusak/vim-dadbod-completion",
    --"dhruvasagar/vim-zoom",
    --"dhruvasagar/vim-table-mode",
}
